# Generated by Django 3.2.9 on 2021-12-10 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_vehicle_driver_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='driver_id',
            new_name='driver',
        ),
    ]
